version: "3.3"

services:
  bot:
    image: "trivia_bot" 
    ports:
      - "8000:8000"
    env_file:
      - "bot.env"
    volumes:
      - ./log:/vol/log

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    
