# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.8' 
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64' 

      - name: Install packages
        run: |
          python -m pip install mypy
          python -m pip install requests
          python -m pip install dataclasses-json
          python -m pip install pydantic
          python -m pip install fastapi
          python -m pip install aiohttp
          python -m pip install redis
          python3 -m pip install types-request
          python3 -m pip install types-redis

      # Runs unit tests
      - name: Run unit tests
        run: |
          echo running tests
          cd $GITHUB_WORKSPACE/trivia/test
          python -m unittest discover -t ..

      # Runs mypy
      - name: Run type check
        run: |
          echo running type check
          cd $GITHUB_WORKSPACE/trivia
          python -m mypy .
